In [3]:
import pandas as pd
import numpy as np

In [27]:
dogs = pd.read_csv("dogs_us_23Jan2023_.csv")
dogs['breeds.primary'] = dogs['breeds.primary'].str.lower()
dogs.head(5)

,id,organization_id,url,type,species,age,gender,size,coat,tags,...,contact.address.address1,contact.address.address2,contact.address.city,contact.address.state,contact.address.postcode,contact.address.country,animal_id,animal_type,organization_id.1,primary_photo_cropped
0,59541454,ON588,https://www.petfinder.com/dog/daisy-59541454/o...,Dog,Dog,Adult,Female,Small,Short,"['Friendly', 'Affectionate', 'Playful']",...,NaN,NaN,Toronto,ON,M4S 0A7,CA,59541454,dog,on588,NaN
1,59541453,SC11,https://www.petfinder.com/dog/happy-nov-22-595...,Dog,Dog,Adult,Male,Large,NaN,[],...,NaN,NaN,Pacolet,SC,29372,US,59541453,dog,sc11,NaN
2,59541450,CA2999,https://www.petfinder.com/dog/bonbom-59541450/...,Dog,Dog,Young,Female,Small,NaN,"['Loyal', 'Playful', 'Smart', 'Protective', 'B...",...,NaN,NaN,Ramona,CA,92065,US,59541450,dog,ca2999,NaN
3,59541447,CT566,https://www.petfinder.com/dog/sugar-59541447/n...,Dog,Dog,Baby,Female,Large,Medium,"['Friendly', 'Affectionate', 'Loyal', 'Gentle'...",...,NaN,NaN,Chatham,NJ,07928,US,59541447,dog,ct566,NaN
4,59541446,TN850,https://www.petfinder.com/dog/darling-59541446...,Dog,Dog,Adult,Female,Medium,NaN,"['At Risk', 'Heartworm Positive']",...,2350 Appling City Cove,NaN,Memphis,TN,38133,US,59541446,dog,tn850,NaN

In [31]:
akc = pd.read_csv("akc_updated.csv")
akc.rename(columns = {'Unnamed: 0': 'Breed'}, inplace = True)
akc['Breed'] = akc['Breed'].str.lower()
akc.head(5)

,Breed,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,affenpinscher,The Affenâ€™s apish look has been described many...,"Confident, Famously Funny, Fearless",148,22.86,29.21,3.175147,4.535924,12.0,15.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing
1,afghan hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113,63.50,68.58,22.679619,27.215542,12.0,15.0,...,0.8,Daily Brushing,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary
2,airedale terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60,58.42,58.42,22.679619,31.751466,11.0,14.0,...,0.6,2-3 Times a Week Brushing,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
3,akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47,60.96,71.12,31.751466,58.967008,10.0,13.0,...,0.8,Daily Brushing,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive
4,alaskan malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58,58.42,63.50,34.019428,38.555351,10.0,14.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly

In [32]:
df_merged=pd.merge(dogs, akc, left_on='breeds.primary', right_on='Breed', how='left')
df_merged.head(5)

,id,organization_id,url,type,species,age,gender,size,coat,tags,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,59541454,ON588,https://www.petfinder.com/dog/daisy-59541454/o...,Dog,Dog,Adult,Female,Small,Short,"['Friendly', 'Affectionate', 'Playful']",...,0.4,Weekly Brushing,0.4,Occasional,1.0,Needs Lots of Activity,0.6,Agreeable,0.8,Friendly
1,59541453,SC11,https://www.petfinder.com/dog/happy-nov-22-595...,Dog,Dog,Adult,Male,Large,NaN,[],...,1.0,Specialty/Professional,0.2,Infrequent,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
2,59541450,CA2999,https://www.petfinder.com/dog/bonbom-59541450/...,Dog,Dog,Young,Female,Small,NaN,"['Loyal', 'Playful', 'Smart', 'Protective', 'B...",...,1.0,Specialty/Professional,0.2,Infrequent,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
3,59541447,CT566,https://www.petfinder.com/dog/sugar-59541447/n...,Dog,Dog,Baby,Female,Large,Medium,"['Friendly', 'Affectionate', 'Loyal', 'Gentle'...",...,0.4,Weekly Brushing,0.6,Seasonal,1.0,Needs Lots of Activity,0.4,Independent,0.4,Reserved with Strangers
4,59541446,TN850,https://www.petfinder.com/dog/darling-59541446...,Dog,Dog,Adult,Female,Medium,NaN,"['At Risk', 'Heartworm Positive']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df_merged.columns

Index(['id', 'organization_id', 'url', 'type', 'species', 'age', 'gender',
       'size', 'coat', 'tags', 'name', 'description_x',
       'organization_animal_id', 'photos', 'videos', 'status',
       'status_changed_at', 'published_at', 'distance', 'breeds.primary',
       'breeds.secondary', 'breeds.mixed', 'breeds.unknown', 'colors.primary',
       'colors.secondary', 'colors.tertiary', 'attributes.spayed_neutered',
       'attributes.house_trained', 'attributes.declawed',
       'attributes.special_needs', 'attributes.shots_current',
       'environment.children', 'environment.dogs', 'environment.cats',
       'primary_photo_cropped.small', 'primary_photo_cropped.medium',
       'primary_photo_cropped.large', 'primary_photo_cropped.full',
       'contact.email', 'contact.phone', 'contact.address.address1',
       'contact.address.address2', 'contact.address.city',
       'contact.address.state', 'contact.address.postcode',
       'contact.address.country', 'animal_id', 'animal_type',
       'organization_id.1', 'primary_photo_cropped', 'Breed', 'description_y',
       'temperament', 'popularity', 'min_height', 'max_height', 'min_weight',
       'max_weight', 'min_expectancy', 'max_expectancy', 'group',
       'grooming_frequency_value', 'grooming_frequency_category',
       'shedding_value', 'shedding_category', 'energy_level_value',
       'energy_level_category', 'trainability_value', 'trainability_category',
       'demeanor_value', 'demeanor_category'],
      dtype='object')

In [34]:
df_filtered = df_merged[['id', 'type', 'species', 'age', 'gender', 'size', 'coat', 'name', 'distance', 'breeds.primary', 'breeds.secondary', 'breeds.mixed','breeds.unknown', 'colors.primary', 'animal_type', 'distance','contact.address.city', 'contact.address.state', 'contact.address.postcode','contact.address.country','Breed', 'description_y','temperament', 'popularity', 'min_height', 'max_height', 'min_weight','max_weight', 'min_expectancy', 'max_expectancy', 'group','grooming_frequency_value', 'grooming_frequency_category','shedding_value', 'shedding_category', 'energy_level_value','energy_level_category', 'trainability_value', 'trainability_category','demeanor_value', 'demeanor_category']]
df_filtered.head(10)

,id,type,species,age,gender,size,coat,name,distance,breeds.primary,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,59541454,Dog,Dog,Adult,Female,Small,Short,Daisy,NaN,jack russell terrier,...,0.4,Weekly Brushing,0.4,Occasional,1.0,Needs Lots of Activity,0.6,Agreeable,0.8,Friendly
1,59541453,Dog,Dog,Adult,Male,Large,NaN,Happy Nov 22,NaN,standard poodle,...,1.0,Specialty/Professional,0.2,Infrequent,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
2,59541450,Dog,Dog,Young,Female,Small,NaN,Bonbom,NaN,poodle,...,1.0,Specialty/Professional,0.2,Infrequent,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
3,59541447,Dog,Dog,Baby,Female,Large,Medium,Sugar,NaN,great pyrenees,...,0.4,Weekly Brushing,0.6,Seasonal,1.0,Needs Lots of Activity,0.4,Independent,0.4,Reserved with Strangers
4,59541446,Dog,Dog,Adult,Female,Medium,NaN,Darling,NaN,mixed breed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,59541444,Dog,Dog,Young,Male,Large,NaN,Lucky,NaN,great pyrenees,...,0.4,Weekly Brushing,0.6,Seasonal,1.0,Needs Lots of Activity,0.4,Independent,0.4,Reserved with Strangers
6,59541438,Dog,Dog,Baby,Male,Large,Short,Davis,NaN,hound,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,59541435,Dog,Dog,Adult,Male,Large,Medium,HATCHI,NaN,akita,...,0.8,Daily Brushing,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive
8,59414553,Dog,Dog,Young,Male,Large,Short,Bogey Bear,NaN,labrador retriever,...,0.4,Weekly Brushing,0.8,Regularly,1.0,Needs Lots of Activity,1.0,Eager to Please,1.0,Outgoing
9,59541433,Dog,Dog,Baby,Male,Large,NaN,Drake,NaN,hound,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df_filtered.to_csv("cleaned_joined_akc_pf.csv", index=False, sep='|')