In [1]:
import pandas as pd
import numpy as np

In [2]:
dogs = pd.read_csv("Aviva/dogs_18_months.csv")
dogs['breeds.primary'] = dogs['breeds.primary'].str.lower()
dogs.head(5)

,id,organization_id,url,type,species,age,gender,size,coat,tags,...,contact.address.address1,contact.address.address2,contact.address.city,contact.address.state,contact.address.postcode,contact.address.country,animal_id,animal_type,organization_id.1,primary_photo_cropped
0,60064676,MN254,https://www.petfinder.com/dog/bruno-mars-60064...,Dog,Dog,Adult,Male,Medium,NaN,['Playful'],...,NaN,NaN,Minneapolis,MN,55407,US,60064676,dog,mn254,NaN
1,60064678,MN254,https://www.petfinder.com/dog/tansy-60064678/m...,Dog,Dog,Young,Female,Small,NaN,['Playful'],...,NaN,NaN,Minneapolis,MN,55407,US,60064678,dog,mn254,NaN
2,60064677,MN254,https://www.petfinder.com/dog/petey-60064677/m...,Dog,Dog,Baby,Male,Small,NaN,['High Energy'],...,NaN,NaN,Minneapolis,MN,55407,US,60064677,dog,mn254,NaN
3,60064681,MN254,https://www.petfinder.com/dog/janet-60064681/m...,Dog,Dog,Young,Female,Medium,NaN,['Playful'],...,NaN,NaN,Minneapolis,MN,55407,US,60064681,dog,mn254,NaN
4,60064680,MN254,https://www.petfinder.com/dog/cola-60064680/mn...,Dog,Dog,Baby,Male,Small,NaN,['High Energy'],...,NaN,NaN,Minneapolis,MN,55407,US,60064680,dog,mn254,NaN

In [3]:
dogs.columns

Index(['id', 'organization_id', 'url', 'type', 'species', 'age', 'gender',
       'size', 'coat', 'tags', 'name', 'description', 'organization_animal_id',
       'photos', 'videos', 'status', 'status_changed_at', 'published_at',
       'distance', 'breeds.primary', 'breeds.secondary', 'breeds.mixed',
       'breeds.unknown', 'colors.primary', 'colors.secondary',
       'colors.tertiary', 'attributes.spayed_neutered',
       'attributes.house_trained', 'attributes.declawed',
       'attributes.special_needs', 'attributes.shots_current',
       'environment.children', 'environment.dogs', 'environment.cats',
       'primary_photo_cropped.small', 'primary_photo_cropped.medium',
       'primary_photo_cropped.large', 'primary_photo_cropped.full',
       'contact.email', 'contact.phone', 'contact.address.address1',
       'contact.address.address2', 'contact.address.city',
       'contact.address.state', 'contact.address.postcode',
       'contact.address.country', 'animal_id', 'animal_type',
       'organization_id.1', 'primary_photo_cropped'],
      dtype='object')

In [4]:
dogs['breeds.primary'].unique()

array(['american staffordshire terrier', 'boxer', 'american bulldog',
       'great pyrenees', 'german shepherd dog',
       'staffordshire bull terrier', 'miniature poodle',
       'english bulldog', 'australian cattle dog / blue heeler',
       'cane corso', 'shetland sheepdog / sheltie', 'newfoundland dog',
       'pug', 'beagle', 'black labrador retriever',
       'cavalier king charles spaniel', 'chocolate labrador retriever',
       'jack russell terrier', 'shepherd', 'dutch shepherd',
       'flat-coated retriever', 'german shorthaired pointer',
       'yellow labrador retriever', 'havanese', 'australian shepherd',
       'rat terrier', 'poodle', 'treeing walker coonhound', 'shar-pei',
       'akita', 'chihuahua', 'border terrier', 'miniature pinscher',
       'great dane', 'australian kelpie', 'cocker spaniel',
       'norwegian elkhound', 'siberian husky', 'border collie',
       'schnauzer', 'labrador retriever', 'pit bull terrier',
       'pomeranian', 'plott hound', 'boston terrier', 'maltese',
       'dachshund', 'cairn terrier', 'corgi', 'alaskan malamute', 'hound',
       'husky', 'golden retriever', 'rottweiler', 'basenji',
       'doberman pinscher', 'french bulldog', 'rhodesian ridgeback',
       'mixed breed', 'miniature schnauzer', 'shiba inu',
       'catahoula leopard dog', 'chow chow', 'presa canario',
       'old english sheepdog', 'leonberger', 'collie',
       'black and tan coonhound', 'english shepherd', 'yorkshire terrier',
       'bernese mountain dog', 'puli', 'greyhound', 'fox terrier',
       'american eskimo dog', 'english pointer', 'maltipoo',
       'miniature dachshund', 'cattle dog', 'german pinscher',
       'white german shepherd', 'bolognese', 'italian greyhound',
       'labradoodle', 'dogue de bordeaux', 'terrier', 'papillon',
       'shih poo', 'aussiedoodle', 'cockapoo', 'chiweenie',
       'irish wolfhound', 'feist', 'standard poodle',
       'anatolian shepherd', 'shih tzu', 'belgian shepherd / malinois',
       'basset hound', 'pointer', 'norfolk terrier', 'mountain cur',
       'black mouth cur', 'pharaoh hound', 'dogo argentino',
       'wirehaired terrier', 'carolina dog', 'norwich terrier',
       'bull terrier', 'retriever', 'german spitz', 'american foxhound',
       'wheaten terrier', 'standard schnauzer', 'silky terrier',
       'west highland white terrier / westie', 'coonhound', 'schipperke',
       'wirehaired dachshund', 'bearded collie', 'spitz',
       'xoloitzcuintli / mexican hairless', 'vizsla', 'affenpinscher',
       'setter', 'bluetick coonhound', 'bichon frise',
       'english springer spaniel', 'saint bernard', 'spaniel',
       'lhasa apso', 'dalmatian', 'pekingese', 'mastiff', 'goldendoodle',
       'keeshond', 'parson russell terrier', 'wire fox terrier',
       'bullmastiff', 'brittany spaniel', 'spanish water dog',
       'american bully', 'afghan hound', 'bernedoodle',
       'airedale terrier', 'brussels griffon', 'jindo',
       'glen of imaal terrier', 'manchester terrier', 'gordon setter',
       'weimaraner', 'scottish terrier', 'bloodhound', 'whippet',
       'tibetan spaniel', 'giant schnauzer', 'foxhound', 'boerboel',
       'sheep dog', 'cavapoo', 'patterdale terrier / fell terrier',
       'australian terrier', 'petit basset griffon vendeen',
       'german wirehaired pointer', 'rough collie',
       'chesapeake bay retriever', 'english foxhound', 'sheepadoodle',
       'chinese crested dog', 'morkie', 'english cocker spaniel',
       'maremma sheepdog', 'pembroke welsh corgi', 'pomsky',
       'redbone coonhound', 'akbash', 'greater swiss mountain dog',
       'caucasian sheepdog / caucasian ovtcharka', 'canaan dog',
       'blue lacy', 'beauceron', 'neapolitan mastiff', 'puggle',
       'cavachon', 'belgian shepherd / laekenois', 'coton de tulear',
       'nova scotia duck tolling retriever', 'otterhound',
       'boykin spaniel', 'belgian shepherd / tervuren', 'samoyed',
       'tibetan terrier', 'skye terrier', 'klee kai', 'toy fox terrier',
       'english setter', 'smooth fox terrier', 'smooth collie',
       'japanese chin', 'mcnab', 'harrier', 'mountain dog', 'schnoodle',
       'cardigan welsh corgi', 'wirehaired pointing griffon',
       'english coonhound', 'toy manchester terrier', 'finnish spitz',
       'bedlington terrier', 'dandie dinmont terrier', 'kyi leo',
       'lancashire heeler', 'irish setter', 'portuguese podengo',
       'irish terrier', 'finnish lapphund', 'welsh terrier',
       'curly-coated retriever', 'tennessee treeing brindle', 'briard',
       'ibizan hound', 'portuguese water dog',
       'belgian shepherd / sheepdog', 'clumber spaniel', 'eskimo dog',
       'scottish deerhound', 'lurcher', 'pyrenean shepherd',
       'norwegian lundehund', 'appenzell mountain dog',
       'miniature bull terrier', 'norwegian buhund', 'swedish vallhund',
       'kerry blue terrier', 'karelian bear dog', 'icelandic sheepdog',
       'entlebucher', 'lakeland terrier', 'polish lowland sheepdog',
       'saluki', 'fila brasileiro', 'south russian ovtcharka'],
      dtype=object)

In [5]:
akc = pd.read_csv("akc_updated.csv")
akc.rename(columns = {'Unnamed: 0': 'Breed'}, inplace = True)
akc['Breed'] = akc['Breed'].str.lower()
akc.head(5)

,Breed,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,affenpinscher,The Affenâ€™s apish look has been described many...,"Confident, Famously Funny, Fearless",148,22.86,29.21,3.175147,4.535924,12.0,15.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing
1,afghan hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113,63.50,68.58,22.679619,27.215542,12.0,15.0,...,0.8,Daily Brushing,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary
2,airedale terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60,58.42,58.42,22.679619,31.751466,11.0,14.0,...,0.6,2-3 Times a Week Brushing,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
3,akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47,60.96,71.12,31.751466,58.967008,10.0,13.0,...,0.8,Daily Brushing,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive
4,alaskan malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58,58.42,63.50,34.019428,38.555351,10.0,14.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly

In [6]:
df_merged=pd.merge(dogs, akc, left_on='breeds.primary', right_on='Breed', how='left')
df_merged.head(5)

,id,organization_id,url,type,species,age,gender,size,coat,tags,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,60064676,MN254,https://www.petfinder.com/dog/bruno-mars-60064...,Dog,Dog,Adult,Male,Medium,NaN,['Playful'],...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
1,60064678,MN254,https://www.petfinder.com/dog/tansy-60064678/m...,Dog,Dog,Young,Female,Small,NaN,['Playful'],...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
2,60064677,MN254,https://www.petfinder.com/dog/petey-60064677/m...,Dog,Dog,Baby,Male,Small,NaN,['High Energy'],...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
3,60064681,MN254,https://www.petfinder.com/dog/janet-60064681/m...,Dog,Dog,Young,Female,Medium,NaN,['Playful'],...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
4,60064680,MN254,https://www.petfinder.com/dog/cola-60064680/mn...,Dog,Dog,Baby,Male,Small,NaN,['High Energy'],...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive

In [7]:
df_merged.columns

Index(['id', 'organization_id', 'url', 'type', 'species', 'age', 'gender',
       'size', 'coat', 'tags', 'name', 'description_x',
       'organization_animal_id', 'photos', 'videos', 'status',
       'status_changed_at', 'published_at', 'distance', 'breeds.primary',
       'breeds.secondary', 'breeds.mixed', 'breeds.unknown', 'colors.primary',
       'colors.secondary', 'colors.tertiary', 'attributes.spayed_neutered',
       'attributes.house_trained', 'attributes.declawed',
       'attributes.special_needs', 'attributes.shots_current',
       'environment.children', 'environment.dogs', 'environment.cats',
       'primary_photo_cropped.small', 'primary_photo_cropped.medium',
       'primary_photo_cropped.large', 'primary_photo_cropped.full',
       'contact.email', 'contact.phone', 'contact.address.address1',
       'contact.address.address2', 'contact.address.city',
       'contact.address.state', 'contact.address.postcode',
       'contact.address.country', 'animal_id', 'animal_type',
       'organization_id.1', 'primary_photo_cropped', 'Breed', 'description_y',
       'temperament', 'popularity', 'min_height', 'max_height', 'min_weight',
       'max_weight', 'min_expectancy', 'max_expectancy', 'group',
       'grooming_frequency_value', 'grooming_frequency_category',
       'shedding_value', 'shedding_category', 'energy_level_value',
       'energy_level_category', 'trainability_value', 'trainability_category',
       'demeanor_value', 'demeanor_category'],
      dtype='object')

In [8]:
df_filtered = df_merged[['id', 'type', 'species', 'age', 'gender', 'size', 'coat', 'name', 'distance', 'breeds.primary', 'breeds.secondary', 'breeds.mixed','breeds.unknown', 'colors.primary', 'animal_type', 'distance','contact.address.city', 'contact.address.state', 'contact.address.postcode','contact.address.country','Breed', 'description_y','temperament', 'popularity', 'min_height', 'max_height', 'min_weight','max_weight', 'min_expectancy', 'max_expectancy', 'group','grooming_frequency_value', 'grooming_frequency_category','shedding_value', 'shedding_category', 'energy_level_value','energy_level_category', 'trainability_value', 'trainability_category','demeanor_value', 'demeanor_category']]
df_filtered.head(10)

,id,type,species,age,gender,size,coat,name,distance,breeds.primary,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,60064676,Dog,Dog,Adult,Male,Medium,NaN,Bruno Mars,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
1,60064678,Dog,Dog,Young,Female,Small,NaN,Tansy,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
2,60064677,Dog,Dog,Baby,Male,Small,NaN,Petey,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
3,60064681,Dog,Dog,Young,Female,Medium,NaN,Janet,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
4,60064680,Dog,Dog,Baby,Male,Small,NaN,Cola,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
5,60064679,Dog,Dog,Baby,Male,Small,NaN,Paddington,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
6,60064682,Dog,Dog,Young,Male,Medium,NaN,Fiddle,NaN,boxer,...,0.4,Weekly Brushing,0.4,Occasional,0.8,Energetic,0.8,Easy Training,1.0,Outgoing
7,60064684,Dog,Dog,Baby,Female,Medium,NaN,Van,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
8,60064687,Dog,Dog,Baby,Male,Small,NaN,Murphy,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive
9,60064688,Dog,Dog,Young,Male,Medium,NaN,Casey,NaN,american staffordshire terrier,...,0.2,Occasional Bath/Brush,0.4,Occasional,0.6,Regular Exercise,0.6,Agreeable,0.6,Alert/Responsive

In [9]:
df_filtered.to_csv("dogs_18_joined_akc_pf_temp.csv", index=False, sep='|')

In [10]:
df_filtered.columns

Index(['id', 'type', 'species', 'age', 'gender', 'size', 'coat', 'name',
       'distance', 'breeds.primary', 'breeds.secondary', 'breeds.mixed',
       'breeds.unknown', 'colors.primary', 'animal_type', 'distance',
       'contact.address.city', 'contact.address.state',
       'contact.address.postcode', 'contact.address.country', 'Breed',
       'description_y', 'temperament', 'popularity', 'min_height',
       'max_height', 'min_weight', 'max_weight', 'min_expectancy',
       'max_expectancy', 'group', 'grooming_frequency_value',
       'grooming_frequency_category', 'shedding_value', 'shedding_category',
       'energy_level_value', 'energy_level_category', 'trainability_value',
       'trainability_category', 'demeanor_value', 'demeanor_category'],
      dtype='object')

In [13]:

df_filtered['max_expectancy'].describe()

count    45360.000000
mean        13.837081
std          2.182304
min          0.000000
25%         12.000000
50%         14.000000
75%         16.000000
max         19.000000
Name: max_expectancy, dtype: float64

In [14]:
len(df_filtered)

61610